theme: jekyll-theme-midnight
title: Somu - The SysAdmin's notes to using RHEL 7.
description: Red Hat Linux 7 System Administration Notes. Based on Pearson Learning's RHEL 7 RHCE and RHCSA course by Sander Van Gurt.
